name: Deploy zabaan-e-kissan-ui to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir Zabaan-E-Kissan
          cp -r .next public package.json package-lock.json next.config.ts Zabaan-E-Kissan/
          cd Zabaan-E-Kissan
          npm install --production

      - name: Zip deployment package
        run: |
          cd Zabaan-E-Kissan
          zip -r ../Zabaan-E-Kissan.zip . > /dev/null 2>&1

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SERVER_IP: ${{ secrets.DROPLET_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

          scp -i ssh_key -o StrictHostKeyChecking=no Zabaan-E-Kissan-ui.zip \
            $SSH_USER@$SERVER_IP:/home/deploy

          ssh -i ssh_key -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
            find /home/deploy/Zabaan-E-Kissan -mindepth 1 -delete
            unzip -o /home/deploy/Zabaan-E-Kissan.zip -d /home/deploy/Zabaan-E-Kissan > /dev/null 2>&1
            cp -r /home/deploy/config/Zabaan-E-Kissan/. /home/deploy/Zabaan-E-Kissan
            cd /home/deploy/Zabaan-E-Kissan
           
            pm2 restart ecosystem.config.cjs --env production || pm2 start ecosystem.config.cjs --env production
            rm /tmp/Zabaan-E-Kissan.zip
          EOF

      - name: Clean up
        run: rm -f ssh_key Zabaan-E-Kissan.zip